name: check-build
run-name: Ensure that ${{ github.sha }} (${{ github.ref }}) builds
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
      - run: nix flake check
